name: Build

on: [push]

defaults:
  run:
    shell: bash

jobs:
  Build:
    name: Build release binaries

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.11

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip pyinstaller pytest
          pip install .

      - name: Build with pyinstaller
        run: pyinstaller --onefile --name=USB_M-${{ matrix.os }} ./src/scripts/main.py

      - name: Deploy artifacts
        uses: actions/upload-artifact@v2
        with:
          name: USB_M-${{ matrix.os }}
          path: USB_M/dist/USB_M-${{ matrix.os }}*
          if-no-files-found: error
